import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AdminHead from "@/components/AdminHead";
import AdminFoot from "@/components/AdminFoot";
// import Footer from "@/components/Footer";
// import Header from "@/components/Header";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// app/admin/layout.js


export default function AdminLayout({ children }) {
    return (
        <html lang="en" className="h-full">
            <body
                className={`${geistSans.variable} ${geistMono.variable} bg-gray-50 antialiased min-h-screen flex flex-col box-border m-0 p-0`}
            >
                <AdminHead />
                <main className="flex-1">{children}</main>
                <AdminFoot />
            </body>
        </html>
    );
}
